version: '3.4'

services:
  supplier.api:
    image: ${DOCKER_REGISTRY-}supplierapi
    build:
      context: .
      dockerfile: Supplier.Api/Dockerfile

  supplier.app:
    image: ${DOCKER_REGISTRY-}supplierapp
    build:
      context: .
      dockerfile: src/BFF/Site/Supplier.App/Dockerfile

